import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import { sanityClient, urlFor } from '../lib/sanity'

import styles from './index.module.css'

const recipesQuery = `*[_type == "recipe"]{
  _id,
  name,
  slug,
  mainImage
}`;

export default function Home({ recipes }) {


  return (
    <div className={styles.container}>
      <Head>
        <title>Recipes &amp; Groceries</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Lets cook some recipes</h1>

      <ul className={styles.recipesList}>
        {recipes?.length > 0 && recipes.map((recipe) => (
          <li key={recipe._id} className={styles.recipeCard}>
            <Link href={`/recipes/${recipe.slug.current}`}>
              <a>
                {/* <Image src={urlFor(recipe.mainImage).url()} width={500} layout="responsive" alt={recipe.name}/> */}
                <img src={urlFor(recipe.mainImage).url()} alt={recipe.name}/>
                <span>{recipe.name}</span>
              </a>
            </Link>
          </li>
        ))}
      </ul>
    </div>
  )
}


// We await this function so that on build time Next.js will prerender this page using these fetched props. 
export async function getStaticProps() {
  const recipes = await sanityClient.fetch(recipesQuery)
  return { props: { recipes } }
}